package de.timscho.jextract;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class JextractRealDownloadTest {

    @TempDir
    Path testProjectDir;

    private File projectDir;
    private File buildFile;
    private File settingsFile;

    @BeforeEach
    void setup() throws Exception {
        this.projectDir = this.testProjectDir.toFile();
        this.buildFile = new File(this.projectDir, "build.gradle");
        this.settingsFile = new File(this.projectDir, "settings.gradle");
    }

    @Test
    void pluginDownloadsDefaultVersionAutomatically() throws Exception {
        // 1. Create a minimal valid C header
        final Path cDir = this.testProjectDir.resolve("src/main/c");
        Files.createDirectories(cDir);
        Files.writeString(cDir.resolve("math.h"), """
            int add(int a, int b);
            int subtract(int a, int b);
        """);

        JextractTestUtils.writeSettingsScript(this.settingsFile.toPath(), "jextract-auto-test");

        // 2. Write Build Script
        JextractTestUtils.writeBuildScript(
                this.buildFile.toPath(),
                null,
                JextractTestUtils.LibraryDefinition.builder()
                        .name("math")
                        .headerFile("src/main/c/math.h")
                        .targetPackage("com.example.math")
                        .build());

        // 3. Run Build
        final BuildResult result = GradleRunner.create()
                .withProjectDir(this.projectDir)
                .withArguments("build", "--info") // Info logs will show the download URL being used
                .withPluginClasspath()
                .forwardOutput()
                .build();

        // 4. Verify
        assertEquals(TaskOutcome.SUCCESS, result.task(":generateMathBindings").getOutcome());

        final Path generatedFile =
                this.testProjectDir.resolve("build/generated/sources/jextract/math/com/example/math/math_h.java");
        assertTrue(Files.exists(generatedFile), "Bindings should be generated by the downloaded tool");

        final String content = Files.readString(generatedFile);
        assertTrue(content.contains("add"), "Generated file should contain the 'add' function");
    }
}
