package de.timscho.jextract;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class JextractRealDownloadTest {

    @TempDir
    Path testProjectDir;

    private File projectDir;
    private File buildFile;
    private File settingsFile;

    @BeforeEach
    void setup() {
        this.projectDir = this.testProjectDir.toFile();
        this.buildFile = new File(this.projectDir, "build.gradle");
        this.settingsFile = new File(this.projectDir, "settings.gradle");
    }

    @Test
    void pluginDownloadsDefaultVersionAutomatically() throws Exception {
        // Arrange
        final Path cDir = this.testProjectDir.resolve("src/main/c");
        Files.createDirectories(cDir);
        Files.writeString(cDir.resolve("math.h"), """
            int add(int a, int b);
            int subtract(int a, int b);
        """);

        JextractTestUtils.writeSettingsScript(this.settingsFile.toPath(), "jextract-auto-test");

        JextractTestUtils.writeBuildScript(
                this.buildFile.toPath(),
                null,
                JextractTestUtils.LibraryDefinition.builder()
                        .name("math")
                        .headerFile("src/main/c/math.h")
                        .targetPackage("com.example.math")
                        .build());

        // Act
        final BuildResult result = GradleRunner.create()
                .withProjectDir(this.projectDir)
                .withArguments("build", "--info") // Info logs will show the download URL being used
                .withPluginClasspath()
                .forwardOutput()
                .build();

        // Assert
        assertThat(result.task(":generateMathBindings").getOutcome()).isEqualTo(TaskOutcome.SUCCESS);

        final Path generatedFile =
                this.testProjectDir.resolve("build/generated/sources/jextract/math/com/example/math/math_h.java");
        assertThat(generatedFile)
                .as("Bindings should be generated by the downloaded tool")
                .exists();

        final String content = Files.readString(generatedFile);
        assertThat(content)
                .as("Generated file should contain the 'add' function")
                .contains("add");
    }
}
