name: "Setup Java and Gradle Environment"
description: "Setup Java and Gradle environment for building"

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: TimSchoenle/actions/actions/java-gradle/setup-base-environment@a63f068514bb35df7d47fc3ae366171d7976395f # actions-java-gradle-setup-base-environment-v1.2.0
      with:
        java_version: "25"

