name: "Setup Java and Gradle Environment"
description: "Setup Java and Gradle environment for building"

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: TimSchoenle/actions/actions/java-gradle/setup-base-environment@478ac4b0c6d4df979618f856207f3f1fdba5b67e # tag=actions-java-gradle-setup-base-environment-v1.2.8
      with:
        java_version: "25"

