name: "Setup Java and Gradle Environment"
description: "Setup Java and Gradle environment for building"

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: TimSchoenle/actions/actions/java-gradle/setup-base-environment@638a417e6a9aef7e78f850ffb30c0475d4e49387 # tag=actions-java-gradle-setup-base-environment-v1.2.4
      with:
        java_version: "25"

