name: Cleanup Branch Caches After Deletion
on:
  delete:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  cleanup-caches:
    name: Cleanup Caches
    if: github.event.ref_type == 'branch'
    uses: TimSchoenle/actions/.github/workflows/maintenance-wipe-cache.yaml@5f3dc8e9600c6b877ee0e4c7b7b85c12dedb4d7b # workflows-maintenance-wipe-cache-v1.1.2
    permissions:
      actions: write # to delete caches
      contents: read # to list cache keys
    with:
      branch: '${{ github.event.ref }}'
      repository: '${{ github.repository }}'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
